### ISSUE TITLE
SSH Channel getting closed while executing RPC call

### ISSUE THREAD

**Issue by MohitDhudiya** [Juniper/netconf-java#20]
Getting exception while executing RPC call using 'executeRPC' API.
**Version** :-  NETCONF Java Toolkit v1.0.2
Probable reason:- After Hello message handshake with Netconf device, it is closing channel. So when we try to execute 'executeRPC' API using 'net.juniper.netconf.Device', it gives below exception.

Exception:- 
---------------
Exception in thread "main" ch.ethz.ssh2.channel.ChannelClosedException: SSH channel is closed. (Close requested by remote)
	at ch.ethz.ssh2.channel.ChannelManager.sendData(ChannelManager.java:426)
	at ch.ethz.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:71)
	at ch.ethz.ssh2.channel.ChannelOutputStream.write(ChannelOutputStream.java:77)
	at net.juniper.netconf.NetconfSession.getRpcReply(NetconfSession.java:82)
	at net.juniper.netconf.NetconfSession.executeRPC(NetconfSession.java:219)
	at net.juniper.netconf.Device.executeRPC(Device.java:530)
	at NetConfPlugin.main(NetConfPlugin.java:18)

Sample Code:-
[NetConfPlugin.txt](https://github.com/Juniper/netconf-java/files/3153045/NetConfPlugin.txt)

**Comment by peterjhill** [comment]
It looks like the channel closed or never connected before you sent the executeRpc command. https://github.com/Juniper/netconf-java/pull/21 will refactor much of this code and error handling. 

This should throw a NetconfException with info on what failed. In the end, the remote side closed the channel.
