### ISSUE TITLE
INVALID_CHARACTER_ERR

### ISSUE THREAD

**Issue by asgharhussaindev** [Juniper/netconf-java#27]
I am getting an invalid character when changing the input on line 37 of examples/EditConfiguration.java as follows:

XML ftp_config = builder.createNewConfig("interfaces", "ge-0/0/11", "description", "TEST");

The error stack is as follows:

Exception in thread "main" org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
	at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.createElement(CoreDocumentImpl.java:665)
	at net.juniper.netconf.XMLBuilder.createNewConfig(XMLBuilder.java:148)
	at EditConfiguration.main(EditConfiguration.java:37)

Any help much appreciated.

**Comment by ydnath** [comment]
Hello @asgharhussaindev Are you able to reachout to JTAC/SE/RE?

**Comment by asgharhussaindev** [comment]
I have not tried that because I didnt know if Juniper would provide support for this type of issue, when there is a GITHUB forum. 

Let me try and see if I get anywhere.

**Comment by asgharhussaindev** [comment]
No what I did figure (for Python code) out from some other forums was that
the timeout value is actually in Milliseconds. So when I changed the
timeout values to 10,000, the connections lost issue was fixed for me.

Thanks.

-Asghar
